<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';
import jsQR from 'jsqr';
import { adminApi } from '../api';

const emit=defineEmits<{checkedIn:[message:string]}>();
const video=ref<HTMLVideoElement|null>(null);const code=ref('');const active=ref(false);const busy=ref(false);const error=ref('');const success=ref('');const photoBusy=ref(false);
let stream:MediaStream|null=null;let frame=0;let lastScan=0;let nativeDetector:any=null;

function detector(){if(nativeDetector)return nativeDetector;const Detector=(window as any).BarcodeDetector;if(!Detector)return null;nativeDetector=new Detector({formats:['qr_code']});return nativeDetector;}
function qrFromCanvas(source:CanvasImageSource,width:number,height:number){const scale=Math.min(1,960/Math.max(width,height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)return '';context.drawImage(source,0,0,canvas.width,canvas.height);const image=context.getImageData(0,0,canvas.width,canvas.height);return jsQR(image.data,image.width,image.height,{inversionAttempts:'attemptBoth'})?.data||'';}
async function submit(value=code.value){const normalized=String(value||'').trim();if(!normalized||busy.value)return;busy.value=true;error.value='';success.value='';try{const result=await adminApi.redeemCheckInCode(normalized);success.value=`${result.order.customerName||'顾客'} · ${result.order.serviceName||'预约'} 已核销`;emit('checkedIn',success.value);code.value='';stop();}catch(err){error.value=err instanceof Error?err.message:'核销失败';}finally{busy.value=false;}}
async function scanFrame(timestamp=0){if(!active.value||!video.value)return;if(timestamp-lastScan<220){frame=window.requestAnimationFrame(scanFrame);return;}lastScan=timestamp;let value='';try{const scanner=detector();if(scanner){const matches=await scanner.detect(video.value);value=matches[0]?.rawValue||'';}else if(video.value.readyState>=2){value=qrFromCanvas(video.value,video.value.videoWidth,video.value.videoHeight);}}catch{}if(value){await submit(value);return;}frame=window.requestAnimationFrame(scanFrame);}
async function start(){error.value='';success.value='';if(!navigator.mediaDevices?.getUserMedia){error.value='当前浏览器无法实时调用相机，请拍照识别。';return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});active.value=true;await new Promise<void>((resolve)=>setTimeout(resolve,50));if(video.value){video.value.srcObject=stream;await video.value.play();frame=window.requestAnimationFrame(scanFrame);}}catch{error.value='无法打开相机，请允许相机权限或使用拍照识别。';stop();}}
async function scanPhoto(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file||photoBusy.value)return;photoBusy.value=true;error.value='';success.value='';const url=URL.createObjectURL(file);try{const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('图片读取失败'));image.src=url;});const value=qrFromCanvas(image,image.naturalWidth,image.naturalHeight);if(!value)throw new Error('照片中没有识别到核销二维码');await submit(value);}catch(err){error.value=err instanceof Error?err.message:'照片识别失败';}finally{URL.revokeObjectURL(url);photoBusy.value=false;}}
function stop(){active.value=false;if(frame)window.cancelAnimationFrame(frame);frame=0;stream?.getTracks().forEach(track=>track.stop());stream=null;if(video.value)video.value.srcObject=null;}
onBeforeUnmount(stop);
</script>

<template><section class="checkin-scanner"><div class="scanner-copy"><span class="scanner-mark">⌁</span><h2>到店核销</h2></div><div v-if="active" class="scanner-camera"><video ref="video" muted playsinline></video><i></i><button class="soft-button" @click="stop">关闭相机</button></div><div class="scanner-actions"><button v-if="!active" class="primary-button" :disabled="busy" @click="start">相机扫码</button><label class="soft-button scanner-photo" :class="{disabled:busy||photoBusy}">{{photoBusy?'识别中…':'拍照识别'}}<input type="file" accept="image/*" capture="environment" :disabled="busy||photoBusy" @change="scanPhoto"/></label><div class="scanner-manual"><input v-model="code" placeholder="粘贴核销内容" @keyup.enter="submit()"/><button class="soft-button" :disabled="busy||!code.trim()" @click="submit()">{{busy?'核销中…':'确认'}}</button></div></div><p v-if="error" class="field-error">{{error}}</p><p v-if="success" class="inline-success">{{success}}</p></section></template>
