<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { adminApi } from '../api';
import type { MySchedule, TechnicianDayPlan } from '../types';
import CheckInScanner from './CheckInScanner.vue';
const props=defineProps<{technicianId?:string}>();
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date());
const date=ref(today());const data=ref<MySchedule|null>(null);const draft=ref<TechnicianDayPlan|null>(null);const loading=ref(true);const saving=ref(false);const error=ref('');const notice=ref('');let request=0;
const selectedLabel=computed(()=>date.value.replace(/-/g,'.'));
const weekdays=['周日','周一','周二','周三','周四','周五','周六'];
function weekday(value:string){return weekdays[new Date(value+'T12:00:00+08:00').getDay()];}
function time(value:number){return new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai',hour12:false}).format(new Date(value));}
async function load(){const id=++request;loading.value=true;error.value='';try{const result=props.technicianId?await adminApi.previewTechnicianSchedule(props.technicianId,date.value):await adminApi.mySchedule(date.value);if(id!==request)return;data.value=result;draft.value=JSON.parse(JSON.stringify(result.plan));}catch(err){if(id===request)error.value=err instanceof Error?err.message:'加载失败';}finally{if(id===request)loading.value=false;}}
async function save(){if(!draft.value||saving.value)return;saving.value=true;error.value='';notice.value='';try{if(props.technicianId)await adminApi.saveScheduleDay(draft.value);else await adminApi.saveMySchedule(draft.value);notice.value='排班已保存';await load();}catch(err){error.value=err instanceof Error?err.message:'保存失败';}finally{saving.value=false;}}
function addShift(){draft.value?.shifts.push({start:'10:00',end:'20:00',breaks:[]});}
watch(date,load);onMounted(load);
</script>
<template><section class="personal-schedule"><div class="page-intro"><div><h1>我的排班</h1></div><button class="soft-button" :disabled="saving" @click="load">刷新</button></div><div v-if="data" class="personal-hero"><div class="personal-identity"><img v-if="data.technician.avatarUrl" :src="data.technician.avatarUrl" alt=""/><div v-else class="team-avatar-placeholder">{{data.technician.name.slice(0,1)}}</div><div><h2>{{data.technician.name}}</h2><p>{{data.technician.title}}</p></div></div><div class="personal-stats"><strong>{{data.days.filter(d=>!d.leave).length}}</strong><span>未来两周工作日</span></div><div class="personal-stats"><strong>{{data.days.reduce((sum,d)=>sum+d.occupancyCount,0)}}</strong><span>已预约时段</span></div></div>
 <CheckInScanner @checked-in="()=>load()"/>
 <p v-if="error" class="field-error" role="alert">{{error}}</p><p v-if="notice" class="inline-success" role="status">{{notice}}</p>
 <div class="schedule-date-toolbar"><h2>未来两周</h2><input v-model="date" type="date" :min="today()" :disabled="saving" aria-label="查看排班日期"/></div>
 <div v-if="data" class="personal-calendar"><button v-for="day in data.days" :key="day.date" :disabled="saving" :class="{selected:date===day.date,rest:day.leave}" @click="date=day.date"><span>{{weekday(day.date)}}</span><strong>{{Number(day.date.slice(8))}}</strong><span>{{day.leave?'休息':day.shifts.map(s=>s.start+'—'+s.end).join(' / ')||'未排班'}}</span><small>{{day.occupancyCount?day.occupancyCount+' 个预约':'—'}}</small></button></div>
 <div v-if="loading" class="loading-state"><div class="loader"></div></div>
 <div v-else-if="draft&&data" class="personal-columns"><section class="panel personal-editor"><div class="panel-heading"><h2>{{selectedLabel}} · {{weekday(date)}}</h2><span :class="['pill',draft.leave?'sand':'green']">{{draft.leave?'休息':'工作日'}}</span></div><label class="switch-row"><span>当天休息</span><input v-model="draft.leave" type="checkbox" :disabled="saving"/></label><div v-if="!draft.leave" class="personal-shifts"><div v-for="(shift,index) in draft.shifts" :key="index" class="personal-shift"><div class="shift-time-row"><label>开始<input v-model="shift.start" type="time" step="900" :disabled="saving"/></label><span>—</span><label>结束<input v-model="shift.end" type="time" step="900" :disabled="saving"/></label><button class="text-button" :disabled="saving" @click="draft.shifts.splice(index,1)">移除</button></div><div v-for="(pause,pauseIndex) in shift.breaks" :key="pauseIndex" class="break-time-row"><span>休息</span><input v-model="pause.start" type="time" step="900" :disabled="saving" aria-label="休息开始时间"/><span>—</span><input v-model="pause.end" type="time" step="900" :disabled="saving" aria-label="休息结束时间"/><button class="text-button" :disabled="saving" @click="shift.breaks.splice(pauseIndex,1)">移除</button></div><button class="text-button" :disabled="saving" @click="shift.breaks.push({start:shift.start,end:shift.start})">＋ 休息时段</button></div><button class="soft-button" :disabled="saving||draft.shifts.length>=8" @click="addShift">＋ 添加班次</button></div><div class="personal-editor-footer"><button class="primary-button" :disabled="saving||date<today()" @click="save">{{saving?'保存中…':'保存当天排班'}}</button></div></section><section class="panel personal-orders"><div class="panel-heading"><h2>当天预约</h2><span>{{data.orders.length}} 单</span></div><div v-for="order in data.orders" :key="order.id" class="personal-order"><span class="order-clock">{{order.startAtLabel}}</span><div><h3>{{order.work?.title || order.serviceName}}</h3><p>{{order.customerName || '预约顾客'}} · {{order.statusLabel}}</p></div></div><p v-if="!data.orders.length" class="empty-inline">当天暂无预约</p><div v-if="draft.occupiedIntervals.length" class="occupied-summary"><h3>已占用时段</h3><span v-for="slot in draft.occupiedIntervals" :key="slot.startAt">{{time(slot.startAt)}} — {{time(slot.endAt)}}</span></div></section></div>
</section></template>
