<script setup lang="ts">
import { computed, ref } from 'vue';
import type { CatalogResponse, Technician } from '../types';
import { adminApi } from '../api';
import ImageUploader from './ImageUploader.vue';
const props=defineProps<{catalog:CatalogResponse}>();const emit=defineEmits<{changed:[];schedule:[id:string];workspace:[id:string]}>();
const draft=ref<any>(null);const busy=ref(false);const uploading=ref(false);const error=ref('');const filter=ref('');
const loginDraft=ref<{technicianId:string;name:string;username:string;password:string}|null>(null);
const members=computed(()=>props.catalog.technicians.filter(t=>!filter.value||t.name.includes(filter.value)));
function edit(tech?:Technician){error.value='';draft.value=tech?{...tech,skills:[...tech.skills],previewUrl:tech.avatarUrl,avatarUrl:tech.avatarFileID||tech.avatarUrl||''}:{name:'',title:'',bio:'',avatarUrl:'',skills:[],enabled:true};if(draft.value)delete draft.value.avatarFileID;}
async function save(){if(busy.value||uploading.value)return;busy.value=true;error.value='';try{await adminApi.saveTechnician({...draft.value,id:draft.value.id||(draft.value.id=crypto.randomUUID())});draft.value=null;emit('changed');}catch(err){error.value=err instanceof Error?err.message:'保存失败';}finally{busy.value=false;}}
function openLogin(tech:Technician){error.value='';loginDraft.value={technicianId:tech.id,name:tech.name,username:'',password:''};}
async function createLogin(){if(!loginDraft.value)return;busy.value=true;error.value='';try{await adminApi.createTechnicianLogin(loginDraft.value.technicianId,loginDraft.value.username,loginDraft.value.password);loginDraft.value=null;emit('changed');}catch(err){error.value=err instanceof Error?err.message:'开通失败';}finally{busy.value=false;}}
</script>
<template><section class="team-studio"><div class="page-intro"><h1>技师管理</h1><button class="primary-button" @click="edit()">＋ 新增技师</button></div><div class="studio-toolbar"><div class="team-summary"><strong>{{catalog.technicians.filter(t=>t.enabled).length}}</strong> 位在岗技师</div><input v-model="filter" class="search-field" placeholder="搜索技师" aria-label="搜索技师"/></div><p v-if="error&&!draft" class="field-error" role="alert">{{error}}</p>
 <div class="team-grid"><article v-for="tech in members" :key="tech.id" class="team-tile"><div class="team-tile-top"><img v-if="tech.avatarUrl" :src="tech.avatarUrl" alt=""/><div v-else class="team-avatar-placeholder">{{tech.name.slice(0,1)}}</div><span :class="['pill',tech.enabled?'green':'sand']">{{tech.enabled?'在岗':'停用'}}</span></div><h2>{{tech.name}}</h2><p>{{tech.title || '技师'}}</p><div class="skill-chips"><span v-for="id in tech.skills" :key="id">{{catalog.services.find(s=>s.id===id)?.name || '已停用项目'}}</span></div><div class="team-actions"><button class="soft-button" @click="edit(tech)">编辑资料</button><button class="primary-button" @click="emit('schedule',tech.id)">查看排班</button></div><button class="workspace-link" @click="emit('workspace',tech.id)">个人工作台 ↗</button><div class="team-binding"><span>{{tech.bound?'账号：'+tech.loginName:'未开通登录账号'}}</span><button v-if="!tech.bound" class="text-button" :disabled="busy||!tech.enabled" @click="openLogin(tech)">开通登录账号</button></div></article><button class="add-tile" @click="edit()"><span>＋</span>新增技师</button></div>
 <div v-if="draft" class="editor-backdrop"><section class="studio-modal" role="dialog" aria-modal="true" aria-label="编辑技师"><header><h2>{{draft.id?'编辑技师':'新增技师'}}</h2><button class="icon-button" :disabled="busy||uploading" @click="draft=null" aria-label="关闭编辑">×</button></header><form @submit.prevent="save"><div class="modal-content"><ImageUploader v-model="draft.avatarUrl" :preview-url="draft.previewUrl" label="上传技师照片" @busy="uploading=$event"/><div class="modal-fields"><label>技师姓名<input v-model="draft.name" required maxlength="80" placeholder="填写姓名"/></label><label>职位<input v-model="draft.title" maxlength="80" placeholder="例如：美甲师"/></label><label>个人介绍<textarea v-model="draft.bio" maxlength="500" rows="3"/></label><fieldset class="skill-picker"><legend>可接待项目</legend><label v-for="service in catalog.services" :key="service.id"><input v-model="draft.skills" :value="service.id" type="checkbox"/><span>{{service.name}}</span></label></fieldset><label class="switch-row"><span>在岗接单</span><input v-model="draft.enabled" type="checkbox"/></label></div></div><p v-if="error" role="alert" class="modal-error">{{error}}</p><footer><button class="soft-button" type="button" :disabled="busy||uploading" @click="draft=null">取消</button><button class="primary-button" :disabled="busy||uploading">{{busy?'保存中…':'保存技师'}}</button></footer></form></section></div>
 <div v-if="loginDraft" class="editor-backdrop"><section class="compact-modal" role="dialog" aria-modal="true" aria-label="开通技师账号"><h2>为{{loginDraft.name}}开通登录账号</h2><form class="modal-fields" @submit.prevent="createLogin"><label>登录账号<input v-model="loginDraft.username" required autocomplete="off" pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,31}" placeholder="3 到 32 位字母或数字"/></label><label>初始密码<input v-model="loginDraft.password" required type="password" autocomplete="new-password" minlength="8" maxlength="32"/></label><p class="form-help">密码至少包含大小写字母、数字、符号中的三类，长度 8 到 32 位。</p><p v-if="error" class="field-error" role="alert">{{error}}</p><div class="toolbar-actions"><button type="button" class="soft-button" :disabled="busy" @click="loginDraft=null">取消</button><button class="primary-button" :disabled="busy">{{busy?'开通中…':'开通账号'}}</button></div></form></section></div>
</section></template>
