-- 卸甲改为免费预约叠加项；建构保留原价并叠加时长。
-- 注意：应用读取时兼容 MySQL JSON_SET 将 TRUE/FALSE 保存为 1/0 的情况。
UPDATE `services` SET `data` = JSON_SET(`data`, '$.priceFen', 0, '$.isAddon', TRUE, '$.addonType', 'REMOVAL', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 WHERE `id` = 'svc-nail-removal-natural';
UPDATE `services` SET `data` = JSON_SET(`data`, '$.priceFen', 0, '$.isAddon', TRUE, '$.addonType', 'REMOVAL', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 WHERE `id` = 'svc-nail-removal-thick-builder';
UPDATE `services` SET `data` = JSON_SET(`data`, '$.priceFen', 0, '$.isAddon', TRUE, '$.addonType', 'REMOVAL', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 WHERE `id` = 'svc-nail-removal-tips';
UPDATE `services` SET `data` = JSON_SET(`data`, '$.isAddon', TRUE, '$.addonType', 'BUILDER', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 WHERE `id` IN ('svc-nail-addon-v-builder', 'svc-nail-addon-shaping-builder', 'svc-nail-addon-luxury-shaping-builder');

INSERT INTO `services` (`id`, `data`, `created_at`, `updated_at`) VALUES ('svc-foot-nail-removal-natural', JSON_OBJECT('_id','svc-foot-nail-removal-natural','id','svc-foot-nail-removal-natural','categoryId','foot-nail','categoryName','脚部美甲','name','卸脚部本甲','description','预约脚部美甲时免费叠加。','priceFen',0,'durationMinutes',30,'coverUrl','','tags',JSON_ARRAY('卸除','本甲'),'sort',19,'enabled',TRUE,'version',1,'isAddon',TRUE,'addonType','REMOVAL','bookableStandalone',FALSE,'createdAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000,'updatedAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) ON DUPLICATE KEY UPDATE `data` = JSON_SET(`data`, '$.priceFen', 0, '$.durationMinutes', 30, '$.isAddon', TRUE, '$.addonType', 'REMOVAL', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000;
INSERT INTO `services` (`id`, `data`, `created_at`, `updated_at`) VALUES ('svc-foot-nail-removal-tips', JSON_OBJECT('_id','svc-foot-nail-removal-tips','id','svc-foot-nail-removal-tips','categoryId','foot-nail','categoryName','脚部美甲','name','卸脚甲片','description','预约脚部美甲时免费叠加。','priceFen',0,'durationMinutes',40,'coverUrl','','tags',JSON_ARRAY('卸除','脚甲片'),'sort',20,'enabled',TRUE,'version',1,'isAddon',TRUE,'addonType','REMOVAL','bookableStandalone',FALSE,'createdAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000,'updatedAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) ON DUPLICATE KEY UPDATE `data` = JSON_SET(`data`, '$.priceFen', 0, '$.durationMinutes', 40, '$.isAddon', TRUE, '$.addonType', 'REMOVAL', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000;
INSERT INTO `services` (`id`, `data`, `created_at`, `updated_at`) VALUES ('svc-foot-nail-addon-v-builder', JSON_OBJECT('_id','svc-foot-nail-addon-v-builder','id','svc-foot-nail-addon-v-builder','categoryId','foot-nail','categoryName','脚部美甲','name','脚部V建构','description','预约脚部美甲主项目时可叠加。','priceFen',1500,'durationMinutes',30,'coverUrl','','tags',JSON_ARRAY('可叠加','建构'),'sort',21,'enabled',TRUE,'version',1,'isAddon',TRUE,'addonType','BUILDER','bookableStandalone',FALSE,'createdAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000,'updatedAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) ON DUPLICATE KEY UPDATE `data` = JSON_SET(`data`, '$.priceFen', 1500, '$.durationMinutes', 30, '$.isAddon', TRUE, '$.addonType', 'BUILDER', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000;
INSERT INTO `services` (`id`, `data`, `created_at`, `updated_at`) VALUES ('svc-foot-nail-addon-shaping-builder', JSON_OBJECT('_id','svc-foot-nail-addon-shaping-builder','id','svc-foot-nail-addon-shaping-builder','categoryId','foot-nail','categoryName','脚部美甲','name','脚部塑形建构','description','预约脚部美甲主项目时可叠加。','priceFen',3000,'durationMinutes',45,'coverUrl','','tags',JSON_ARRAY('可叠加','建构'),'sort',22,'enabled',TRUE,'version',1,'isAddon',TRUE,'addonType','BUILDER','bookableStandalone',FALSE,'createdAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000,'updatedAt',UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) ON DUPLICATE KEY UPDATE `data` = JSON_SET(`data`, '$.priceFen', 3000, '$.durationMinutes', 45, '$.isAddon', TRUE, '$.addonType', 'BUILDER', '$.bookableStandalone', FALSE, '$.updatedAt', UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000), `updated_at` = UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000;
